# frozen_string_literal: true

source 'https://rubygems.org'

ruby(File.read(File.join(File.dirname(__FILE__), '.ruby-version')).strip)

gem 'debug'
gem 'rspec'
gem 'rubocop', require: false
gem 'ruby-lsp'
